spring.application.name=hie-fhir-exchange-service
server.port=${SERVER_PORT:8086}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://discovery-server:8761/eureka/}
eureka.instance.prefer-ip-address=true

auth.identity.base-url=${AUTH_IDENTITY_BASE_URL:http://auth-identity-service:8081}
consent.service.base-url=${CONSENT_SERVICE_BASE_URL:http://consent-service:8082}
hospital-a.service.base-url=${HOSPITAL_A_SERVICE_BASE_URL:http://hospital-a-service:8083}
hospital-b.service.base-url=${HOSPITAL_B_SERVICE_BASE_URL:http://hospital-b-service:8084}
notification-audit.service.base-url=${NOTIFICATION_AUDIT_SERVICE_BASE_URL:http://notification-audit-service:8087}
app.cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:5173,http://localhost:5174,http://localhost:5175}
app.internal.service-token=${INTERNAL_SERVICE_TOKEN:change-me-before-service-splitting}
jwt.secret=${JWT_SECRET:change-me-to-a-256-bit-base64-secret-in-prod-at-least-32-chars}
jwt.access-token-expiry-seconds=${JWT_ACCESS_TOKEN_EXPIRY_SECONDS:3600}
jwt.refresh-token-expiry-seconds=${JWT_REFRESH_TOKEN_EXPIRY_SECONDS:604800}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true
info.app.name=hie-fhir-exchange-service
info.app.phase=phase-6-docker
